# xMICD: Example Usage Notebook

This notebook demonstrates how to use the `xMICD` class to:

- Load ICD code embeddings  
- Load the hierarchical grouping structure  
- Build the xMICD model from these inputs  
- Retrieve vector representations for individual ICD codes or aggregated sets of codes  

Each section introduces one step of the workflow and can be adapted to your own data.

## 1. Set up

We begin by importing the required libraries and loading the ICD embedding matrix.

In [1]:
from xMICD import xMICD
import pandas as pd

### Load embedding matrix

The file `icd_code_vec.csv` contains pre-trained embeddings for ICD codes, typically one vector per code.

The embedding file is loaded into `embedding_df`.  
Each row corresponds to one ICD code, and the remaining columns store its embedding dimensions.
The columns are renamed with the prefix `Embedding_` to match the expected format of `xMICD`.

In [2]:
embedding_df = pd.read_csv("Input/icd_code_vec.csv")
embedding_df.columns = ["DIS_CODE"]+["Embedding_"+col for col in embedding_df.columns.to_list()[1:]]
embedding_df.head()

,DIS_CODE,Embedding_0,Embedding_1,Embedding_2,Embedding_3,Embedding_4,Embedding_5,Embedding_6,Embedding_7,Embedding_8,...,Embedding_1014,Embedding_1015,Embedding_1016,Embedding_1017,Embedding_1018,Embedding_1019,Embedding_1020,Embedding_1021,Embedding_1022,Embedding_1023
0,A00,0.062662,0.069492,-0.062197,0.027203,-0.122601,0.109749,0.033870,0.011480,-0.158279,...,-0.181965,0.217679,-0.039114,-0.112860,0.220006,-0.119871,0.099518,-0.230879,-0.325332,-0.109664
1,A000,0.067028,0.110111,-0.009773,0.027653,-0.139956,0.113899,-0.014510,-0.056627,-0.092039,...,-0.112203,0.253481,-0.001807,-0.079261,0.216512,-0.110161,0.033945,-0.228332,-0.350511,-0.175411
2,A001,0.012806,-0.073449,-0.194383,0.030890,-0.104823,0.071724,0.255976,0.289722,-0.450981,...,-0.485810,0.057378,-0.200740,-0.266606,0.282643,-0.191786,0.387447,-0.246718,-0.278767,0.134742
3,A009,0.087436,0.119059,-0.020660,0.023321,-0.124710,0.130990,-0.052174,-0.094882,-0.045424,...,-0.065448,0.277363,0.018373,-0.053212,0.190165,-0.089956,-0.014772,-0.222431,-0.332015,-0.198793
4,A01,-0.166250,0.126540,-0.080693,-0.025942,-0.008737,0.047102,-0.038586,0.383638,-0.240688,...,-0.284910,0.111417,0.022381,-0.168525,0.064540,-0.158785,0.043830,-0.392468,-0.507154,0.007472

### Load grouping file

The file `grouping.csv` defines the hierarchical relationships between ICD codes (e.g. parent–child groups).
xMICD uses this structure to construct anchor (group-level) embeddings.

In [3]:
grouping_df = pd.read_csv("Input/grouping.csv")
grouping_df.head()

  ICD_code    Group
0      A00  A00-A09
1     A000  A00-A09
2     A001  A00-A09
3     A009  A00-A09
4      A01  A00-A09

## 3. Build the xMICD model

We now initialize `xMICD` and build the hierarchical embedding structure from:

- the ICD embedding matrix (`embedding_df`)  
- the grouping table (`grouping_df`)  

The argument `method` in `xMICD.build_from_grouping` controls how anchor (group-level) embeddings are constructed:

- `method="similarity"` (default): for each group, selects the ICD code whose embedding has the highest average cosine similarity to other codes in the same group (a “medoid”).  
- `method="mean"`: for each group, computes the anchor as the mean of all available ICD embeddings in that group.  

After this step, the model is ready to answer ICD vector queries.

In [4]:
xMICD = xMICD()
xMICD.build_from_grouping(
  embedding_df=embedding_df,
  grouping_df=grouping_df,
  embeddings_icd_column="DIS_CODE",
  embeddings_embedding_column_prefix="Embedding_",
  groupings_icd_column="ICD_code",
  groupings_group_column="Group",
  method="similarity"
)

You can extract and inspect the anchor table constructed by xMICD.
Anchors represent group-level embeddings derived from the hierarchical ICD structure.

In [5]:
anchor_df = xMICD.get_anchors_df()
anchor_df.head()

,ICD_code,Embedding_0,Embedding_1,Embedding_2,Embedding_3,Embedding_4,Embedding_5,Embedding_6,Embedding_7,Embedding_8,...,Embedding_1014,Embedding_1015,Embedding_1016,Embedding_1017,Embedding_1018,Embedding_1019,Embedding_1020,Embedding_1021,Embedding_1022,Embedding_1023
0,A00-A09,0.016789,0.010529,0.125331,0.010457,-0.198151,0.001793,0.044448,0.181032,-0.417463,...,-0.097866,0.353959,0.051239,-0.071135,0.159027,-0.136780,0.099153,-0.368199,-0.291492,-0.035028
1,A15-A19,0.064626,-0.008522,0.063888,0.037330,-0.014776,0.146857,-0.257068,0.240926,-0.219253,...,-0.100309,0.090913,0.010420,0.084898,0.115204,-0.125848,-0.139514,-0.427525,-0.330940,-0.168843
2,A20-A28,-0.045135,0.073171,0.048047,0.082945,-0.095362,-0.014199,-0.025004,0.413631,-0.218214,...,-0.094656,0.094021,-0.153695,-0.075135,-0.027920,-0.095387,0.085441,-0.295191,-0.304068,0.057431
3,A30-A49,-0.058216,0.043455,-0.108780,0.113253,-0.067487,0.094091,-0.012400,0.221222,-0.155525,...,-0.154410,0.142775,0.042463,-0.160190,-0.001310,0.021940,0.084887,-0.333547,-0.397973,-0.054987
4,A50-A64,-0.015272,0.018028,-0.222336,-0.006442,-0.149869,0.061234,-0.012696,0.417944,-0.105432,...,-0.133328,0.165330,0.051859,-0.155567,0.251349,0.142224,-0.071994,-0.383247,-0.322037,0.053474

You may save this table and later rebuild xMICD using `build_from_anchor` to save time in larger workflows.

In [6]:
# xMICD = xMICD()
# xMICD.build_from_anchor(
#     embedding_df = embedding_df,
#     anchor_df = anchor_df,
#     embeddings_icd_column = "DIS_CODE",
#     embeddings_embedding_column_prefix = "Embedding_",
#     anchor_icd_column = "ICD_code",
#     anchor_embedding_column_prefix = "Embedding_"
# )

# 4. Usage examples

The following sections show how to query vectors from the xMICD model under different settings.

## ICD vectors without parent reduction

Here we request vectors for a list of ICD codes directly, without using parent reduction.
The model returns:

- `valid_icds`: the subset of input codes that can be mapped  
- `icd_vectors`: the corresponding embedding vectors

In [7]:
valid_icds, icd_vectors = xMICD.get_icd_vector(["A00","B03","S52001A"])

C:\Users\Lenovo\Downloads\Thesis\ทุน FF\xMICS_Demo\xMICS_Demo_Kup_s Edition\xMICD.py:124: UserWarning: ICD S52001A does not exist in embedding database. Skipped ICD S52001A
  warnings.warn(f"ICD {icd} does not exist in embedding database. Skipped ICD {icd}")

We first request the vector representation of each ICD code separately.

In [8]:
#Give the embedding of each ICD code separately
print("Valid ICD codes: "+" ".join(valid_icds))
print("ICD vectors: ")
print(icd_vectors)

Valid ICD codes: A00 B03
ICD vectors:
[[0.76249668 0.5678507  0.59392934 1.         0.51789735 0.92361997
  0.55806533 0.78811792 0.92090353 0.87267894 0.7562767  0.59087534
  0.88478868 0.68076455 0.61748728 0.76304769 0.62039575 0.48757289
  0.29011991 0.98748173 0.7157038  0.58948968 0.61893986 0.58625036
  0.51308563 0.50084729 0.55601145 0.45270674 0.71418723 0.71403595
  0.60537056 0.7015945  0.59567914 0.55206741 0.47906068 0.84621332
  0.88891511 0.46848178 0.71576588 0.76163385 0.89418124 0.66567131
  0.41211194 0.81579005 0.43318171 0.76226572 0.62016796 0.79140219
  0.14258626 0.62041221 0.77235459 0.89133591 0.68430404 0.55914748
  0.67881969 0.75264305 0.65497413 0.55558041 0.55798697 0.51851534
  0.6551425  0.56229184 0.94746436 0.33701658 0.4448423  0.3580515
  0.41112319 0.56417974 0.50513608 0.54515497 0.63848294 0.33472257
  0.56692855 0.71825181 0.35604883 0.18559713 0.57710723 0.62960092
  0.29205394 0.0543976  0.25910209 0.49342097 0.39466101 0.87499305
  0.21955314 0.51871603 0.14102222 0.57260627 0.1066891  0.67512056
  0.68951449 0.48202536 0.54018493 0.72470037 0.45066167 0.48415983
  0.39298892 0.55311289 0.46622307 0.48318476 0.48750772 0.37444808
  0.42912422 0.8066008  0.81377696 0.72501124 0.20594715 0.72282803
  0.1580386  0.38026904 0.58761085 0.52673872 0.42070201 0.40844042
  0.45758811 0.78146907 0.46124851 0.76123654 0.42249974 0.49833779
  0.61192698 0.31774956 0.42953376 0.55412808 0.61012443 0.52425698
  0.69599738 0.65317221 0.45267906 0.44562942 0.42469504 0.75238269
  0.54312253 0.4513844  0.36109433 0.40383311 0.34364436 0.37009003
  0.2246504  0.70272656 0.54896726 0.39406921 0.41912029 0.41578573
  0.54156091 0.51180556 0.49369436 0.42853433 0.47312672 0.64142979
  0.72090991 0.62804847 0.68329496 0.77798682 0.56883341 0.18921155
  0.6462226  0.32816744 0.43729052 0.49999861 0.92020695 0.71508816
  0.87289501 0.60838339 0.45740955 0.78190581 0.59716493 0.64175933
  0.51331238 0.84713921 0.38475438 0.56035629 0.4327013  0.36918531
  0.38650231 0.40905957 0.35864781 0.39755322 0.17869186 0.21078711
  0.30514594 0.2917526  0.32709033 0.21437322 0.33887388 0.43143759
  0.89374149 0.         0.32124866 0.21670783 0.4091217  0.58718021
  0.6516747  0.58449336 0.2016072  0.44315048 0.24417226 0.24178555
  0.17062318 0.24655984 0.23181024 0.44552062 0.46963345 0.64668086
  0.45104428 0.42594242 0.57657578 0.66815218 0.75254273]
 [0.29271107 0.62084617 0.58420252 0.89669672 0.5625012  0.9227022
  0.51259767 0.76888335 0.96044763 0.92089031 0.88411885 0.59177453
  1.         0.70277346 0.56429787 0.72082    0.4965533  0.38224841
  0.40997846 0.64785348 0.68863857 0.54912285 0.65351487 0.56441254
  0.47918616 0.47838239 0.54205953 0.36234278 0.68454221 0.75750212
  0.60806725 0.77524833 0.62672683 0.43312951 0.35781812 0.75890175
  0.91787875 0.37776872 0.7303615  0.72106449 0.82848619 0.55225673
  0.38637957 0.77474838 0.35225518 0.7334896  0.56847295 0.81990993
  0.13665552 0.64800194 0.73073789 0.88099736 0.64676299 0.58403413
  0.68829751 0.79751257 0.69199392 0.56903615 0.51990989 0.52281741
  0.65986861 0.49141765 0.94033765 0.33008175 0.35191833 0.34625678
  0.4339526  0.54063646 0.47445078 0.55749158 0.64960657 0.31783533
  0.559372   0.70084114 0.25286202 0.20110586 0.55077203 0.6487274
  0.2808924  0.03737788 0.18443251 0.43037173 0.46927929 0.84663233
  0.21318775 0.49371191 0.12393502 0.56847939 0.09023949 0.67787456
  0.60168609 0.4560336  0.49474309 0.75058133 0.5466774  0.47413422
  0.36882973 0.54704417 0.50011337 0.29299517 0.30148815 0.26449142
  0.33054103 0.67387815 0.63723119 0.76650647 0.09471135 0.65653949
  0.14886706 0.38056565 0.47675834 0.47873846 0.40751617 0.37105255
  0.49581784 0.79343688 0.46312827 0.76131553 0.3928305  0.47229796
  0.62182738 0.30956537 0.29264704 0.47746758 0.51176321 0.46103846
  0.64561036 0.62887771 0.46718792 0.47239287 0.34046779 0.71986283
  0.50814929 0.3877119  0.29763995 0.37329761 0.31075404 0.33496862
  0.1903023  0.610358   0.52582129 0.36666104 0.37692165 0.43047
  0.54028364 0.51526369 0.45602611 0.36583865 0.44610951 0.57982866
  0.73401091 0.59808161 0.62791378 0.77449521 0.64730869 0.17719563
  0.59592373 0.31578851 0.44172218 0.51680475 0.96840548 0.75313121
  0.85628117 0.49867251 0.42465228 0.78010079 0.56720613 0.59486005
  0.48726293 0.85023796 0.40326191 0.45263294 0.42861438 0.40797718
  0.38542127 0.45529662 0.4193657  0.44047829 0.21347024 0.24053181
  0.35349786 0.29633223 0.35657316 0.23680186 0.38129868 0.52597632
  0.89364318 0.         0.2601177  0.18627598 0.36128438 0.53870293
  0.63233616 0.58382037 0.24100745 0.45833431 0.25379529 0.28375988
  0.19004377 0.30552432 0.33699624 0.49551145 0.5211915  0.66404811
  0.44246076 0.50139919 0.53210321 0.64636844 0.77448258]]

### Aggregated embedding

Here we compute a single aggregated vector for the set of ICD codes using the `"max"` aggregation method.

The argument `method` in `xMICD.get_aggregated_vector` controls how individual xMICD vectors are combined:

- `method="max"` (default): elementwise maximum over all ICD vectors.  
- `method="avg"`: elementwise mean over all ICD vectors.  
- `method="avg3top"`: for each dimension, takes the average of the three largest values across ICD vectors.  

You can choose the aggregation strategy depending on whether you want a more “any-code-activates” profile (`max`) or a smoother, averaged profile (`avg` / `avg3top`).

In [9]:
valid_icds, icd_vectors = xMICD.get_aggregated_vector(["A00","B03","S52001A"],method="max")

C:\Users\Lenovo\Downloads\Thesis\ทุน FF\xMICS_Demo\xMICS_Demo_Kup_s Edition\xMICD.py:124: UserWarning: ICD S52001A does not exist in embedding database. Skipped ICD S52001A
  warnings.warn(f"ICD {icd} does not exist in embedding database. Skipped ICD {icd}")

In [10]:
#Give only one aggregated embedding of all ICD codes
print("Valid ICD codes: "+" ".join(valid_icds))
print("Aggregated ICD vector: ")
print(icd_vectors)

Valid ICD codes: A00 B03
Aggregated ICD vector:
[0.76249668 0.62084617 0.59392934 1.         0.5625012  0.92361997
 0.55806533 0.78811792 0.96044763 0.92089031 0.88411885 0.59177453
 1.         0.70277346 0.61748728 0.76304769 0.62039575 0.48757289
 0.40997846 0.98748173 0.7157038  0.58948968 0.65351487 0.58625036
 0.51308563 0.50084729 0.55601145 0.45270674 0.71418723 0.75750212
 0.60806725 0.77524833 0.62672683 0.55206741 0.47906068 0.84621332
 0.91787875 0.46848178 0.7303615  0.76163385 0.89418124 0.66567131
 0.41211194 0.81579005 0.43318171 0.76226572 0.62016796 0.81990993
 0.14258626 0.64800194 0.77235459 0.89133591 0.68430404 0.58403413
 0.68829751 0.79751257 0.69199392 0.56903615 0.55798697 0.52281741
 0.65986861 0.56229184 0.94746436 0.33701658 0.4448423  0.3580515
 0.4339526  0.56417974 0.50513608 0.55749158 0.64960657 0.33472257
 0.56692855 0.71825181 0.35604883 0.20110586 0.57710723 0.6487274
 0.29205394 0.0543976  0.25910209 0.49342097 0.46927929 0.87499305
 0.21955314 0.51871603 0.14102222 0.57260627 0.1066891  0.67787456
 0.68951449 0.48202536 0.54018493 0.75058133 0.5466774  0.48415983
 0.39298892 0.55311289 0.50011337 0.48318476 0.48750772 0.37444808
 0.42912422 0.8066008  0.81377696 0.76650647 0.20594715 0.72282803
 0.1580386  0.38056565 0.58761085 0.52673872 0.42070201 0.40844042
 0.49581784 0.79343688 0.46312827 0.76131553 0.42249974 0.49833779
 0.62182738 0.31774956 0.42953376 0.55412808 0.61012443 0.52425698
 0.69599738 0.65317221 0.46718792 0.47239287 0.42469504 0.75238269
 0.54312253 0.4513844  0.36109433 0.40383311 0.34364436 0.37009003
 0.2246504  0.70272656 0.54896726 0.39406921 0.41912029 0.43047
 0.54156091 0.51526369 0.49369436 0.42853433 0.47312672 0.64142979
 0.73401091 0.62804847 0.68329496 0.77798682 0.64730869 0.18921155
 0.6462226  0.32816744 0.44172218 0.51680475 0.96840548 0.75313121
 0.87289501 0.60838339 0.45740955 0.78190581 0.59716493 0.64175933
 0.51331238 0.85023796 0.40326191 0.56035629 0.4327013  0.40797718
 0.38650231 0.45529662 0.4193657  0.44047829 0.21347024 0.24053181
 0.35349786 0.29633223 0.35657316 0.23680186 0.38129868 0.52597632
 0.89374149 0.         0.32124866 0.21670783 0.4091217  0.58718021
 0.6516747  0.58449336 0.24100745 0.45833431 0.25379529 0.28375988
 0.19004377 0.30552432 0.33699624 0.49551145 0.5211915  0.66404811
 0.45104428 0.50139919 0.57657578 0.66815218 0.77448258]

## Using `use_parent_embedding=True`

When `use_parent_embedding=True`, xMICD can reduce very specific ICD codes (e.g. `A008`)
to a valid parent code (e.g. `A00`) before computing their vectors.

This is useful when:

- some detailed codes are rare or missing  
- you want more stable, higher-level representations of ICD patterns

In [11]:
valid_icds, icd_vectors = xMICD.get_icd_vector(["A00","B03","S52001A"],use_parent_embedding=True)

In [12]:
#With use_parent_embedding, S52001A could be reduced to S520
print("Valid ICD codes: "+" ".join(valid_icds))
print("ICD vectors: ")
print(icd_vectors)

Valid ICD codes: A00 B03 S52001A
ICD vectors:
[[0.76249668 0.5678507  0.59392934 1.         0.51789735 0.92361997
  0.55806533 0.78811792 0.92090353 0.87267894 0.7562767  0.59087534
  0.88478868 0.68076455 0.61748728 0.76304769 0.62039575 0.48757289
  0.29011991 0.98748173 0.7157038  0.58948968 0.61893986 0.58625036
  0.51308563 0.50084729 0.55601145 0.45270674 0.71418723 0.71403595
  0.60537056 0.7015945  0.59567914 0.55206741 0.47906068 0.84621332
  0.88891511 0.46848178 0.71576588 0.76163385 0.89418124 0.66567131
  0.41211194 0.81579005 0.43318171 0.76226572 0.62016796 0.79140219
  0.14258626 0.62041221 0.77235459 0.89133591 0.68430404 0.55914748
  0.67881969 0.75264305 0.65497413 0.55558041 0.55798697 0.51851534
  0.6551425  0.56229184 0.94746436 0.33701658 0.4448423  0.3580515
  0.41112319 0.56417974 0.50513608 0.54515497 0.63848294 0.33472257
  0.56692855 0.71825181 0.35604883 0.18559713 0.57710723 0.62960092
  0.29205394 0.0543976  0.25910209 0.49342097 0.39466101 0.87499305
  0.21955314 0.51871603 0.14102222 0.57260627 0.1066891  0.67512056
  0.68951449 0.48202536 0.54018493 0.72470037 0.45066167 0.48415983
  0.39298892 0.55311289 0.46622307 0.48318476 0.48750772 0.37444808
  0.42912422 0.8066008  0.81377696 0.72501124 0.20594715 0.72282803
  0.1580386  0.38026904 0.58761085 0.52673872 0.42070201 0.40844042
  0.45758811 0.78146907 0.46124851 0.76123654 0.42249974 0.49833779
  0.61192698 0.31774956 0.42953376 0.55412808 0.61012443 0.52425698
  0.69599738 0.65317221 0.45267906 0.44562942 0.42469504 0.75238269
  0.54312253 0.4513844  0.36109433 0.40383311 0.34364436 0.37009003
  0.2246504  0.70272656 0.54896726 0.39406921 0.41912029 0.41578573
  0.54156091 0.51180556 0.49369436 0.42853433 0.47312672 0.64142979
  0.72090991 0.62804847 0.68329496 0.77798682 0.56883341 0.18921155
  0.6462226  0.32816744 0.43729052 0.49999861 0.92020695 0.71508816
  0.87289501 0.60838339 0.45740955 0.78190581 0.59716493 0.64175933
  0.51331238 0.84713921 0.38475438 0.56035629 0.4327013  0.36918531
  0.38650231 0.40905957 0.35864781 0.39755322 0.17869186 0.21078711
  0.30514594 0.2917526  0.32709033 0.21437322 0.33887388 0.43143759
  0.89374149 0.         0.32124866 0.21670783 0.4091217  0.58718021
  0.6516747  0.58449336 0.2016072  0.44315048 0.24417226 0.24178555
  0.17062318 0.24655984 0.23181024 0.44552062 0.46963345 0.64668086
  0.45104428 0.42594242 0.57657578 0.66815218 0.75254273]
 [0.29271107 0.62084617 0.58420252 0.89669672 0.5625012  0.9227022
  0.51259767 0.76888335 0.96044763 0.92089031 0.88411885 0.59177453
  1.         0.70277346 0.56429787 0.72082    0.4965533  0.38224841
  0.40997846 0.64785348 0.68863857 0.54912285 0.65351487 0.56441254
  0.47918616 0.47838239 0.54205953 0.36234278 0.68454221 0.75750212
  0.60806725 0.77524833 0.62672683 0.43312951 0.35781812 0.75890175
  0.91787875 0.37776872 0.7303615  0.72106449 0.82848619 0.55225673
  0.38637957 0.77474838 0.35225518 0.7334896  0.56847295 0.81990993
  0.13665552 0.64800194 0.73073789 0.88099736 0.64676299 0.58403413
  0.68829751 0.79751257 0.69199392 0.56903615 0.51990989 0.52281741
  0.65986861 0.49141765 0.94033765 0.33008175 0.35191833 0.34625678
  0.4339526  0.54063646 0.47445078 0.55749158 0.64960657 0.31783533
  0.559372   0.70084114 0.25286202 0.20110586 0.55077203 0.6487274
  0.2808924  0.03737788 0.18443251 0.43037173 0.46927929 0.84663233
  0.21318775 0.49371191 0.12393502 0.56847939 0.09023949 0.67787456
  0.60168609 0.4560336  0.49474309 0.75058133 0.5466774  0.47413422
  0.36882973 0.54704417 0.50011337 0.29299517 0.30148815 0.26449142
  0.33054103 0.67387815 0.63723119 0.76650647 0.09471135 0.65653949
  0.14886706 0.38056565 0.47675834 0.47873846 0.40751617 0.37105255
  0.49581784 0.79343688 0.46312827 0.76131553 0.3928305  0.47229796
  0.62182738 0.30956537 0.29264704 0.47746758 0.51176321 0.46103846
  0.64561036 0.62887771 0.46718792 0.47239287 0.34046779 0.71986283
  0.50814929 0.3877119  0.29763995 0.37329761 0.31075404 0.33496862
  0.1903023  0.610358   0.52582129 0.36666104 0.37692165 0.43047
  0.54028364 0.51526369 0.45602611 0.36583865 0.44610951 0.57982866
  0.73401091 0.59808161 0.62791378 0.77449521 0.64730869 0.17719563
  0.59592373 0.31578851 0.44172218 0.51680475 0.96840548 0.75313121
  0.85628117 0.49867251 0.42465228 0.78010079 0.56720613 0.59486005
  0.48726293 0.85023796 0.40326191 0.45263294 0.42861438 0.40797718
  0.38542127 0.45529662 0.4193657  0.44047829 0.21347024 0.24053181
  0.35349786 0.29633223 0.35657316 0.23680186 0.38129868 0.52597632
  0.89364318 0.         0.2601177  0.18627598 0.36128438 0.53870293
  0.63233616 0.58382037 0.24100745 0.45833431 0.25379529 0.28375988
  0.19004377 0.30552432 0.33699624 0.49551145 0.5211915  0.66404811
  0.44246076 0.50139919 0.53210321 0.64636844 0.77448258]
 [0.25385982 0.57533671 0.31056006 0.56315041 0.41796403 0.46568992
  0.27905617 0.36352892 0.52132407 0.51734072 0.51569901 0.42136524
  0.31804879 0.49358893 0.41655265 0.402534   0.26801316 0.29320557
  0.43475976 0.36702057 0.42961256 0.58866315 0.57036397 0.46024909
  0.60538837 0.54494782 0.4728122  0.41691761 0.44157802 0.53826156
  0.42403614 0.61951137 0.53560069 0.19926049 0.38995812 0.62625843
  0.64884226 0.42268165 0.54770002 0.59954201 0.57796373 0.41226218
  0.48259359 0.49190369 0.29641645 0.48604053 0.46833279 0.50086323
  0.06214014 0.4614025  0.63102486 0.33620614 0.48073826 0.3986003
  0.54815327 0.55344476 0.48125868 0.6109834  0.61441356 0.40563257
  0.51772029 0.61336447 0.62957675 0.61540217 0.49585284 0.5472544
  0.64186151 0.53948617 0.59048063 0.6635535  0.63703525 0.46201896
  0.5651998  0.64109189 0.51481851 0.46948559 0.55117586 0.68329767
  0.33829016 0.         0.08907575 0.55529175 0.51931223 0.64503152
  0.55028301 0.73989436 0.59994619 0.57209997 0.51969559 0.38200799
  0.52418224 0.57518581 0.3385653  0.51536737 0.53252806 0.56842407
  0.407089   0.61003271 0.724304   0.5140491  0.54709343 0.29839401
  0.45622786 0.72932776 0.36198968 0.64230217 0.3841447  0.6035861
  0.49884367 0.18601986 0.26779677 0.49450768 0.46170878 0.36979816
  0.46033961 0.70291427 0.82603652 0.50652108 0.60507666 0.74029328
  0.90991713 0.70924047 0.1791003  0.55730304 0.13548162 0.51606992
  0.62685307 0.60901111 0.63176292 0.55404487 0.33995661 0.63056398
  0.63019034 0.41668652 0.48931787 0.57246906 0.54362697 0.50701655
  0.28362261 0.53168024 0.44400405 0.5132801  0.38567438 0.60355329
  0.62205887 0.54258197 0.42784449 0.59937324 0.53282581 0.62583112
  0.65269284 0.49922784 0.58653563 0.557948   0.60319932 0.15595611
  0.58856344 0.59573845 0.59390977 0.94178571 0.63217716 0.50943111
  0.63766043 0.53336169 0.39839445 0.69307229 0.60367161 0.66799756
  0.4366192  0.60326261 0.47203636 0.48748553 0.38255342 0.47357706
  0.47116001 0.87631497 0.83839369 0.87756189 0.83473127 0.89895664
  1.         0.84222267 0.86811306 0.8080721  0.89761887 0.32966454
  0.56197667 0.30925204 0.75518679 0.59518735 0.41956748 0.60783982
  0.76250947 0.75097046 0.49184101 0.45992028 0.53728024 0.48020005
  0.47616591 0.30401134 0.35596502 0.54246754 0.52322703 0.51396987
  0.38454423 0.5294211  0.47896145 0.56674175 0.60984749]]

### Aggregated embedding with parent reduction

Finally, we compute an aggregated embedding using the `"max"` method and enabling parent reduction.
This produces a stable representation for the set of ICD codes after mapping them to valid parents.

In [13]:
valid_icds, icd_vectors = xMICD.get_aggregated_vector(["A00","B03","S52001A"],use_parent_embedding=True,method="max")

In [14]:
#With use_parent_embedding, S52001A could be reduced to S520
print("Valid ICD codes: "+" ".join(valid_icds))
print("Aggregated vector: ")
print(icd_vectors)

Valid ICD codes: A00 B03 S52001A
Aggregated vector:
[0.76249668 0.62084617 0.59392934 1.         0.5625012  0.92361997
 0.55806533 0.78811792 0.96044763 0.92089031 0.88411885 0.59177453
 1.         0.70277346 0.61748728 0.76304769 0.62039575 0.48757289
 0.43475976 0.98748173 0.7157038  0.58948968 0.65351487 0.58625036
 0.60538837 0.54494782 0.55601145 0.45270674 0.71418723 0.75750212
 0.60806725 0.77524833 0.62672683 0.55206741 0.47906068 0.84621332
 0.91787875 0.46848178 0.7303615  0.76163385 0.89418124 0.66567131
 0.48259359 0.81579005 0.43318171 0.76226572 0.62016796 0.81990993
 0.14258626 0.64800194 0.77235459 0.89133591 0.68430404 0.58403413
 0.68829751 0.79751257 0.69199392 0.6109834  0.61441356 0.52281741
 0.65986861 0.61336447 0.94746436 0.61540217 0.49585284 0.5472544
 0.64186151 0.56417974 0.59048063 0.6635535  0.64960657 0.46201896
 0.56692855 0.71825181 0.51481851 0.46948559 0.57710723 0.68329767
 0.33829016 0.0543976  0.25910209 0.55529175 0.51931223 0.87499305
 0.55028301 0.73989436 0.59994619 0.57260627 0.51969559 0.67787456
 0.68951449 0.57518581 0.54018493 0.75058133 0.5466774  0.56842407
 0.407089   0.61003271 0.724304   0.5140491  0.54709343 0.37444808
 0.45622786 0.8066008  0.81377696 0.76650647 0.3841447  0.72282803
 0.49884367 0.38056565 0.58761085 0.52673872 0.46170878 0.40844042
 0.49581784 0.79343688 0.82603652 0.76131553 0.60507666 0.74029328
 0.90991713 0.70924047 0.42953376 0.55730304 0.61012443 0.52425698
 0.69599738 0.65317221 0.63176292 0.55404487 0.42469504 0.75238269
 0.63019034 0.4513844  0.48931787 0.57246906 0.54362697 0.50701655
 0.28362261 0.70272656 0.54896726 0.5132801  0.41912029 0.60355329
 0.62205887 0.54258197 0.49369436 0.59937324 0.53282581 0.64142979
 0.73401091 0.62804847 0.68329496 0.77798682 0.64730869 0.18921155
 0.6462226  0.59573845 0.59390977 0.94178571 0.96840548 0.75313121
 0.87289501 0.60838339 0.45740955 0.78190581 0.60367161 0.66799756
 0.51331238 0.85023796 0.47203636 0.56035629 0.4327013  0.47357706
 0.47116001 0.87631497 0.83839369 0.87756189 0.83473127 0.89895664
 1.         0.84222267 0.86811306 0.8080721  0.89761887 0.52597632
 0.89374149 0.30925204 0.75518679 0.59518735 0.41956748 0.60783982
 0.76250947 0.75097046 0.49184101 0.45992028 0.53728024 0.48020005
 0.47616591 0.30552432 0.35596502 0.54246754 0.52322703 0.66404811
 0.45104428 0.5294211  0.57657578 0.66815218 0.77448258]